{{- if and .Values.global.creatioDbCa.enabled .Values.global.creatioDbCa.inlinePem }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.creatioDbCa.secretName }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "gs.name" . }}
type: Opaque
data:
  {{ .Values.global.creatioDbCa.key }}: {{ .Values.global.creatioDbCa.inlinePem | b64enc }}
{{- end }}
