{{- if or (not .Values.global.db.existingSecret) (not .Values.global.rabbitmq.existingSecret) (not .Values.global.redis.existingSecret) (not .Values.global.elasticsearch.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gs-secrets
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "gs.name" . }}
type: Opaque
data:
  {{- if not .Values.global.db.existingSecret }}
  databaseConnectionString: {{ include "db.connectionString" . | b64enc }}
  {{- end }}
  {{- if not .Values.global.rabbitmq.existingSecret }}
  rabbitmqConnectionString: {{ include "rabbitmq.connectionString" . | b64enc }}
  {{- end }}
  {{- if not .Values.global.redis.existingSecret }}
  redisConnectionString: {{ include "redis.connectionString" . | b64enc }}
  {{- if .Values.global.redis.password }}
  redis-password: {{ .Values.global.redis.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if not .Values.global.rabbitmq.existingSecret }}
  {{- if .Values.global.rabbitmq.password }}
  rabbitmq-password: {{ .Values.global.rabbitmq.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if not .Values.global.elasticsearch.existingSecret }}
  {{- if .Values.global.elasticsearch.user }}
  elasticsearchUser: {{ .Values.global.elasticsearch.user | b64enc }}
  {{- else }}
  elasticsearchUser: ""
  {{- end }}
  {{- if .Values.global.elasticsearch.password }}
  elasticsearchPassword: {{ .Values.global.elasticsearch.password | b64enc }}
  {{- else }}
  elasticsearchPassword: ""
  {{- end }}
  {{- end }}
{{- end }}
