{{- if .Values.vault.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-vault-secrets
  labels:
    app: {{ template "gs.name" . }}
    chart: {{ template "gs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider: {{ .Values.vault.csi.provider }}
  parameters:
    vaultAddress: {{ .Values.vault.csi.address | quote }}
    roleName: {{ .Values.vault.csi.role | quote }}
    {{- range .Values.vault.csi.parameters }}
    objects: |
      - objectName: {{ .objectName | quote }}
        secretPath: {{ .secretPath | quote }}
        secretKey: {{ .objectAlias | quote }}
    {{- end }}
  {{- if .Values.vault.csi.secretObjects }}
  secretObjects:
  {{- range .Values.vault.csi.secretObjects }}
    - secretName: {{ .secretName | quote }}
      type: {{ .type | quote }}
      data:
      {{- range .data }}
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
