apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-api
  labels:
    app: {{ .Release.Name }}-web-api
    chart: {{ template "gs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.webApi.replicaCount }}
{{- with .Values.webApi.strategy }}
  strategy:
{{ toYaml . | indent 4  }}
{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-api
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        timestamp: {{ now | quote }}
        {{- if .Values.vault.agentInjector.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.agentInjector.role | quote }}
        vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.agentInjector.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-config: {{ .Values.vault.agentInjector.template | quote }}
        {{- range $key, $value := .Values.vault.agentInjector.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        app: {{ .Release.Name }}-web-api
        release: {{ .Release.Name }}
    spec:
      volumes:
{{- if .Values.vault.csi.enabled }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-vault-secrets
{{- end }}
{{ if .Values.global.elasticsearch.tls.enable }}
        - name: tls-certs
          secret:
            secretName: {{ include "global.elasticsearch.tlsSecretName" . }}
            items:
              - key: {{ .Values.global.elasticsearch.tls.certificate.ca.name }}
                path: {{ .Values.global.elasticsearch.tls.certificate.ca.name }}
{{- end }}
{{ if .Values.global.postgresTls.enable }}
        - name: postgres-tls-certs
          secret:
            secretName: {{ .Values.global.postgresTls.caCertificateSecretName }}
            items:
              - key: {{ .Values.global.postgresTls.caCertificateKey }}
                path: {{ .Values.global.postgresTls.caCertificateKey }}
{{- end }}
{{ if .Values.global.creatioDbCa.enabled }}
        - name: creatio-postgres-ca
          secret:
            secretName: {{ .Values.global.creatioDbCa.secretName }}
            items:
              - key: {{ .Values.global.creatioDbCa.key }}
                path: {{ .Values.global.creatioDbCa.key }}
{{- end }}
{{ if .Values.global.redisTls.enable }}
        - name: redis-tls-certs
          secret:
            secretName: {{ .Values.global.redisTls.caCertificateSecretName }}
            items:
              - key: {{ .Values.global.redisTls.caCertificateKey }}
                path: {{ .Values.global.redisTls.caCertificateKey }}
{{- end }}
        - name: log4net-file
          configMap:
            name: {{ .Release.Name }}-logging-configmap
            items:
              - key: log4net.config
                path: log4net.config
{{ if .Values.webApi.nodeName }}
      nodeName: {{ .Values.webApi.nodeName }}
{{- end }}
{{ if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}
      initContainers:
{{ if .Values.global.elasticsearch.tls.enable }}
        - name: wait-for-es-cert
          image: {{ .Values.busybox.image }}:{{ .Values.busybox.tag }}
          command:
            - sh
            - -c
            - >
              echo "Waiting for Elasticsearch certificate secret...";
              until [ -f {{ .Values.global.elasticsearch.tls.certificate.ca.path }}/{{ .Values.global.elasticsearch.tls.certificate.ca.name }} ];
              do
                echo "Certificate not available yet...";
                sleep 5;
              done;
              echo "Certificate is available. Proceeding...";
          volumeMounts:
            - name: tls-certs
              mountPath: {{ .Values.global.elasticsearch.tls.certificate.ca.path }}
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
{{- end }}
        - name: wait-for-elasticsearch
          image: alpine/curl:8.12.1
          command:
            - sh
            - -c
            - >
              ELASTICSEARCH_URL=$(echo {{ .Values.global.elasticsearch.url }});
              echo "Waiting for Elasticsearch to be available at $ELASTICSEARCH_URL...";
              until curl --silent --fail -k
              --user ${ELASTIC_USER}:${ELASTIC_PASSWORD}
              --max-time 5 --connect-timeout 5
              $ELASTICSEARCH_URL;
              do
                echo "Elasticsearch is not available yet $ELASTICSEARCH_URL...";
                sleep 5;
              done;
              echo "Elasticsearch $ELASTICSEARCH_URL is available and responding. Proceeding...";
          env:
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "elasticsearch.secretName" . }}
                  key: {{ include "elasticsearch.usernameKey" . }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "elasticsearch.secretName" . }}
                  key: {{ include "elasticsearch.passwordKey" . }}
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.webApi.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if .Values.webApi.lifecycle.preStop.enabled }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep {{ .Values.webApi.lifecycle.preStop.sleepSeconds }}"]
{{- end }}
          volumeMounts:
{{ if .Values.global.elasticsearch.tls.enable }}
            - name: tls-certs
              mountPath: {{ .Values.global.elasticsearch.tls.certificate.ca.path }}
              readOnly: true
{{- end }}
{{ if .Values.global.postgresTls.enable }}
            - name: postgres-tls-certs
              mountPath: {{ .Values.global.postgresTls.caCertificatePath | dir }}
              readOnly: true
{{- end }}
{{ if .Values.global.creatioDbCa.enabled }}
            - name: creatio-postgres-ca
              mountPath: {{ .Values.global.creatioDbCa.certificatePath | dir }}
              readOnly: true
{{- end }}
{{ if .Values.global.redisTls.enable }}
            - name: redis-tls-certs
              mountPath: {{ .Values.global.redisTls.caCertificatePath | dir }}
              readOnly: true
{{- end }}
{{- if .Values.vault.csi.enabled }}
            - name: secrets-store
              mountPath: {{ .Values.vault.csi.mountPath }}
              readOnly: true
{{- end }}
            - name: log4net-file
              mountPath: {{ .Values.log4Net.mountPath }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: connectionStrings__db
              valueFrom:
                secretKeyRef:
                  name: {{ include "db.secretName" . }}
                  key: {{ include "db.connectionStringKey" . }}
            - name: connectionStrings__DbType
              value: "{{ .Values.global.db.type }}"
            - name: RedisCacheOptions__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.connectionStringKey" . }}
            - name: RedisTlsOptions__Enable
              value: "{{ .Values.global.redisTls.enable }}"
            - name: RedisTlsOptions__SslHost
              value: "{{ default .Values.global.redis.host .Values.global.redisTls.sslHost }}"
            - name: RedisTlsOptions__CaCertificatePath
              value: "{{ .Values.global.redisTls.caCertificatePath }}"
            - name: RedisCacheOptions__ConnectAttempts
              value: {{ .Values.global.redis.connectAttempts | quote }}
            - name: RedisCacheOptions__ReconnectInterval
              value: {{ .Values.global.redis.reconnectInterval }}
            - name: RedisCacheOptions__DefaultExpiration
              value: {{ .Values.global.redis.defaultExpiration }}
            - name: PostgresTlsOptions__Enable
              value: "{{ .Values.global.postgresTls.enable }}"
            - name: PostgresTlsOptions__SslMode
              value: "{{ .Values.global.postgresTls.sslMode }}"
            - name: PostgresTlsOptions__TrustServerCertificate
              value: "{{ .Values.global.postgresTls.trustServerCertificate }}"
            - name: PostgresTlsOptions__RootCertificatePath
              value: "{{ .Values.global.postgresTls.caCertificatePath }}"
            - name: PostgresTlsOptions__GlobalSearchRootCertificatePath
              value: "{{ .Values.global.postgresTls.caCertificatePath }}"
{{ if .Values.global.creatioDbCa.enabled }}
            - name: PostgresTlsOptions__CreatioRootCertificatePath
              value: "{{ .Values.global.creatioDbCa.certificatePath }}"
{{- end }}
            - name: RequestTimeOut
              value: "{{ .Values.global.requestTimeOut | int64 }}"
            - name: ScheduledIndexationConfiguration__IndexingIntervalInDays
              value: "{{ .Values.global.incrementDays | int64 }}"
            - name: PullIndexationConfiguration__Enabled
              value: "{{ .Values.global.pullIndexationConfigEnabled }}"
            - name: searchServiceUrl
              value: "{{ .Values.global.searchService.url }}"
            - name: elasticSearchUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-global-config-map
                  key: es.url
            - name: elasticLogin
              valueFrom:
                secretKeyRef:
                  name: {{ include "elasticsearch.secretName" . }}
                  key: {{ include "elasticsearch.usernameKey" . }}
            - name: elasticPassword
              valueFrom:
                secretKeyRef:
                  name: {{ include "elasticsearch.secretName" . }}
                  key: {{ include "elasticsearch.passwordKey" . }}
            - name: ElasticSearch__Tls__Enable
              value: "{{ .Values.global.elasticsearch.tls.enable }}"
{{ if .Values.global.elasticsearch.tls.enable }}
            - name: ElasticSearch__Tls__CaCertificatePath
              value: "{{ .Values.global.elasticsearch.tls.certificate.ca.path }}/{{ .Values.global.elasticsearch.tls.certificate.ca.name }}"
{{- end }}
            - name: Log4NetPath
              value: {{ .Values.log4Net.mountPath }}/log4net.config
            - name: IgnoredEntities
              value: "{{ .Values.webApi.env.ignoredEntities }}"
            - name: AuthenticationOptions__IdentityProviderUrl
              value: "{{ .Values.global.identityProvider.url }}"
            - name: AuthenticationOptions__UseOAuth
              value: "{{ .Values.global.identityProvider.useOAuth }}"
            - name: workerThreads
              value: "{{ .Values.webApi.workerThreads | int64  }}"
            - name: completionPortThreads
              value: "{{ .Values.webApi.completionPortThreads | int64  }}"
            - name: CircuitBreaker__Enable
              value: {{ .Values.global.circuitBreaker.enable | quote }}
{{ if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /liveness
              port: http
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
{{- end }}
{{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
{{- end }}
{{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
{{- end }}
          resources:
{{ toYaml .Values.webApi.resources | indent 12 }}
    {{- with .Values.webApi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if or .Values.webApi.affinity .Values.webApi.podAntiAffinity.enabled }}
      affinity:
      {{- if .Values.webApi.podAntiAffinity.enabled }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.webApi.podAntiAffinity.weight }}
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ .Release.Name }}-web-api
                topologyKey: {{ .Values.webApi.podAntiAffinity.topologyKey }}
      {{- end }}
      {{- with .Values.webApi.affinity }}
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.webApi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
